### ISSUE TITLE
本仓库包体过大(244M)，建议清除无用的*.jar历史记录，仓库内用到jar建议转为pom

### ISSUE THREAD

**Issue by addstone** [dromara/dante-cloud#10]
包体过大
看到每次发版都有发布源码，清除历史记录中的大文件对源码几乎无影响。
优点
  1.大部分都是给内用户，git clone 代码时间过长
  2.减少同步代码代码时候的流量消耗，毕竟有些流量是有数量限制的

**Comment by herodotus-ecosystem** [comment]
> 包体过大 看到每次发版都有发布源码，清除历史记录中的大文件对源码几乎无影响。 优点 1.大部分都是给内用户，git clone 代码时间过长 2.减少同步代码代码时候的流量消耗，毕竟有些流量是有数量限制的

没太明白你这个244M是怎么统计出来的，核心代码模块已经单独提取出一个工程，相关的包都已经上传至中央仓库。

直接在 Git 上下载zip，或者源代码目前也只有 不到12M。就算之前的版本是把 Skywalking的 Agent 包含在里面，也不会超过 50M啊。

只有 configurations\docker\context\target，每次编译都会生成Jar这些Jar是为了打包Docker而准备，版本号不变的情况下 maven clean 就会清除相关的包。如果经常更新代码版本，maven clean 执行顺序不对是对会出现这个目录增大的情况，但是也可以通过修改目录解决。

你不会是把本地编译好的工程整体打包了吧，包括：.git、.idea、target，都打成一个包了？

**Comment by addstone** [comment]
我是直接拉取的最新代码，查看.git 文件 ，确实是244M

**Comment by aboutZZ** [comment]
。。。你查看`.git`文件夹那肯定大，毕竟每个提交历史都在那存着。
