### ISSUE TITLE
国家三级等保要求

### ISSUE THREAD

**Issue by john1337** [dromara/dante-cloud#18]
三级等保是满足一定条件的项目才有资格进行的测试吧，请问dante-cloud是如何通过等保三级的？

**Comment by herodotus-ecosystem** [comment]
是借着做项目的机会。项目有要求，花钱请专业的第三方公司进行测评。

**Comment by herodotus-ecosystem** [comment]
满足要求是一方面，评测报告是另一方面。满足要求是指Dante Cloud 在安全设计方面的功能均达到要求，意思是安全性上有保障，相关功能也无需重复开发。但很多项目要求是要有评测报告的，即使功能上满足，还是要重新花钱由第三方测试出报告的。

**Comment by john1337** [comment]
ok
