### ISSUE TITLE
个人拙见

### ISSUE THREAD

**Issue by yunnet** [dromara/dante-cloud#19]
首先表达对作者能开源前后端代码，表达最崇高的敬意，虽然，因受到一些无耻之人的困绕，关闭了Dante Engine的开源，这个开源的权力在你，只是想说，linux也是开源的，否则没有今天的伟大。
个人看了一下作者的代码，封装的很漂亮，但个人感觉有点瑕疵，模块与模块之间，藕合性太强了。如果多使用SPI的动态替换扩展机制，比如接口，只想在运行时动态给它添加一个实现类接口，只需要按照规范给它添加一个实现类即可。如大家熟悉的JDBC中的Driver接口，不同的厂商可以提供不同的实现，如MySQL、Oracle、SQLServer等，

**Comment by herodotus-ecosystem** [comment]
感谢兄弟的认可与支持。你的评价很中肯。你说的 SPI 机制其实就是 Spring Boot 中的动态配置机制，其实已经在Dante Cloud 中大量使用了，特别是对于一些基础模块比如 access、captcha、oss等模块已经用了很多。但是毕竟是一个应用系统，需要各个模块组合使用构建成一套系统，对于上层的模块就很难避免耦合了。

耦合性强这个问题可以说不是瑕疵而是硬伤。前期只是注重功能实现，随着个人对技术以及 Spring 生态的理解与认知的提升和扩展，我也意识到了这个问题，所以在响应式版本中，借着融入响应式的机会，在耦合性方面做了大量的改进。不说彻底改变彻底解决了耦合，但绝对可以说是有了大踏步的进步。未来我也会持续的在这方面改进。

至于说关闭 Dante Engine 开源，不是一时冲动，而是现在环境太差，实在是不得已而为之。对于相关的事情原本是有心理准备的，否则也不会开源了三年多。前面的发生的事情可以说是压死骆驼的最后一根稻草。更多的就不详说了。

但是，考虑到还是有一些朋友一致坚持给与 Dante Cloud 支持，所以目前 Dante Engine 并没有完全闭源，只要在 Gitee 帖子下留言，给 Dante Cloud 点个 Star，就会免费开私库的（不包括响应式版本）。虽然，本质上和开源没区别，就是多了道手续。但是，通过这种方式至少目前看可以帮助筛选出真正喜欢或者想要学习的人，因为伸手党们多一步都懒得做。

所以，如果兄弟你感兴趣可以了解一下。

https://gitee.com/dromara/dante-cloud/issues/I65F5B

![image](https://github.com/user-attachments/assets/474d5b0c-2b18-40bd-b113-b92d38c679f3)

**Comment by yunnet** [comment]
谢谢回复，写代码就像艺术，喜欢就会一直支持。加油。
