### ISSUE TITLE
这个框架支持多类型用户么？

### ISSUE THREAD

**Issue by gdhzzn** [dromara/dante-cloud#2]
先点个start支持下

现在我们打算做的一个项目 有移动端用户和后台管理用户，他们可能不在同一张用户表中，对应的权限也有不同，这个框架能支持分别进行登陆验证和权限控制么

**Comment by herodotus-ecosystem** [comment]
这个问题我感觉是设计和理解问题，关键是看业务和设计。

说实话，我不是特别理解和明白你的需求。

如果不同类型的用户，数据放在不同表中，还用不同的方式登录，不同的权限控制：
1. 如果业务上也没有什么关联，这更像是两个独立系统。如果是不同的系统，每个系统还不是需要有后台管理功能。
2. 如果业务上有关联，按照你的描述，应该是一套系统，两套独立的用户权限体系，涉足相同的业务内容，这个怕是会非常复杂，也很难做的通用。甚至接口要么做多参数控制，要么统一业务做两套接口。

本系统的设计是：用户就是用户，人员就是人员，不同种类的人员可以灵活设计，但是都需要与用户进行关联。换句话说，用户权限体系登录都还是一套，人员可以有不同的种类。

**Comment by gdhzzn** [comment]
> 这个问题我感觉是设计和理解问题，关键是看业务和设计。
> 
> 说实话，我不是特别理解和明白你的需求。
> 
> 如果不同类型的用户，数据放在不同表中，还用不同的方式登录，不同的权限控制：
> 
> 1. 如果业务上也没有什么关联，这更像是两个独立系统。如果是不同的系统，每个系统还不是需要有后台管理功能。
> 2. 如果业务上有关联，按照你的描述，应该是一套系统，两套独立的用户权限体系，涉足相同的业务内容，这个怕是会非常复杂，也很难做的通用。甚至接口要么做多参数控制，要么统一业务做两套接口。
> 
> 本系统的设计是：用户就是用户，人员就是人员，不同种类的人员可以灵活设计，但是都需要与用户进行关联。换句话说，用户权限体系登录都还是一套，人员可以有不同的种类。

是的 就是你说的第二种情况 就像是淘宝 京东这种分成app端买家登陆和后台管理端卖家登陆是走的两套用户逻辑 其实之前有在网上搜索过oauth2 实现多用户类型登陆控制的实现 但都不是特别完美 有点头疼
